apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-sharing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: file-sharing
  template:
    metadata:
      labels:
        app: file-sharing
    spec:
      restartPolicy: Always
      containers:
      - name: file-sharing
        image: marcialvieira/file-sharing:stable
        env:
        - name: DATABASE_URL
          value: "mongodb://mongodb/file-sharing"
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000
        volumeMounts:
          - mountPath: /app/files
            name: data-volume
      volumes:
      - name: data-volume
        hostPath:
          path: /data
